package:
   name: cudatoolkit
   # match the package version to the libcudart.so version
   version: 11.0.171

source:
    path: .

# source downloading is done in build.py. To locally cache and point to your local file,
# set the DEBUG_INSTALLER_PATH environment variable to the folder where you have 
# downloaded the installer

build:
  number: 1
  script_env:
    - NVTOOLSEXT_INSTALL_PATH
    - DEBUG_INSTALLER_PATH
  missing_dso_whitelist:
    - "$RPATH/libdl.so.2"
    - "$RPATH/libpthread.so.0"
    - "$RPATH/libc.so.6"
    - "$RPATH/librt.so.1"
    - "$RPATH/ld-linux-x86-64.so.2"
    - "$RPATH/libm.so.6"

requirements:
  build:
    - 7za # [win]
    - python >=3.7
    - pyyaml
    - requests
    - tqdm
    # for run_exports
    - {{ compiler('cxx') }}

test:
  requires:
    - numba
    - python >=3.7
    - setuptools  # for pkg_resources
